# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
generate_missing_sql_type_definitions = true

[migrations_directory]
dir = "/Users/boruchc/work/analysis-view-vscode-extension/query-engine/migrations"
