apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: query-engine-service
  labels:
    run.googleapis.com/cpu-throttling: "false"
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 20
      timeoutSeconds: 600
      containers:
      - image: gcr.io/PROJECT_ID/query-engine-service:latest
        ports:
        - name: h2c
          containerPort: 50051
        env:
        - name: GRPC_PORT
          value: "50051"
        - name: GCS_BUCKET_NAME
          value: "agentic_analytics_datasets_prod"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: query-engine-database-url
              key: latest
        - name: RUST_LOG
          value: "query_engine_service=info"
        resources:
          limits:
            cpu: "2000m"
            memory: "8Gi"
          requests:
            cpu: "2000m"
            memory: "4Gi"
        livenessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true